[input]
url = "opc.tcp://localhost:4840/OPC_UA_Server"
failoverTimeout = 5000

[output]
url = "opc.tcp://localhost:4840/OPC_UA_Server"
failoverTimeout = 5000

[[measurements]]
collectionType = "polled"
pollRate = 30
nodeIn = "ns=2;i=10849"
nodeOut = "ns=37;i=10849"
deadbandAbsolute   = 0 		# Absolute max difference for a value not to be transferred
deadbandRelative   = 0    	# Relative max difference for a value not to be transferred

#[[measurements]]
#nodeIn = "ns=2;s=10849"
#nodeOut = "ns=37;s=10849"
#collectionType     = "monitored"
#monitorResolution  = 2000    # ms